azure_resource_group_name = "az-resource-grp"
azure_location            = "Central India"
azure_network_name        = "vnet-v"
azure_gateway_cidr        = "10.1.1.0/24"
gcp_project_id            = "gcp-project-id"
gcp_region                = "asia-south2"
gcp_network               = "gcp-vpc"