aws_vpc_id         = "vpc-14124"
aws_region         = "ap-southeast-1"
aws_route_table_id = "rtb-324rew"
gcp_network        = "gcp-vpc"
gcp_project_id     = "gcp-project-id"
gcp_region         = "asia-southeast1"